project:
  type: book

book:
  title: "Radiology DataScience"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/radio-ds-notes
  site-url: https://radio-ds-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Data Architecture
      chapters: 
        - "content/data-architect/database-explained.qmd"
        - "content/data-architect/database-lakehouse.qmd"
        - "content/data-architect/radioclinic-story.qmd"
    - part: CDM
      chapters: 
        - "content/CDM/cdm-overview.qmd"
        - "content/CDM/HL7-FHIR-overview.qmd"
        - "content/CDM/FHIR-foundation.qmd"
        - "content/CDM/FHIR-datatypes.qmd"
    - part: OMOP 
      chapters: 
        - "content/CDM/cdm-omop-sql-explained.qmd"
    - part: CDM — Map
      chapters: 
        - "content/CDM/ConceptMap/FHIR-ConceptMap.qmd"
        - "content/CDM/ConceptMap/Map-DICOM-SNOMED.qmd"
        - "content/CDM/ConceptMap/Map-one-many.qmd"
        - "content/CDM/ConceptMap/Map-flow.qmd"
        - "content/CDM/cdm-map-study-series-image.qmd"
    - part: MI-CDM
      chapters: 
        - "content/CDM/mi-cdm-01.qmd"
    - part: Files in Radiology
      chapters: 
        - "content/dicom.qmd"
        - "content/dicom-tags.qmd"
        - "content/dicom-element-explain.qmd"
        - "content/pydicom.ipynb"
        - "content/pydicom-tags.ipynb"
        - "content/nifti.qmd"
        - "content/mrml-mrb.qmd"
        - "content/nrrd-intro.qmd"
        - "content/nrrd-pynrrd.ipynb"
    - part: DICOM Communication
      chapters: 
        - "content/DICOM/dicom-AE.qmd"
    - part: Radiomics
      chapters:
        - "content/radiomics-wf.qmd"
    - part: Pyradiomics
      chapters: 
        - "content/pyradiomics/pyradiomics-intro.qmd"
        - "content/pyradiomics/PyRadiomicsExample.ipynb"
        - "content/pyradiomics/pyradiomics-extract-df.ipynb"
        - "content/pyradiomics/pyradiomics-params-mr.qmd"
    - part: "3D Slicer"
      chapters:
        - "content/slicer/slicer-intro.qmd"
        - "content/slicer/slicer-MR-field-correct.qmd"
        - "content/slicer/slicer-segment.qmd"
    - part: "LLM"
      chapters:
        - "content/LLM/recist-extract-basic.ipynb"
    - part: "Idea"
      chapters: 
        - "idea/report-search.qmd"
    - references.qmd


bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc-depth: 4
    code-fold: show

execute: 
  freeze: auto



