project:
  type: book

book:
  title: "Radiology DataScience"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/radio-ds-notes
  site-url: https://radio-ds-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Basic
      chapters: 
        - "content/dicom.qmd"
        - "content/pydicom.ipynb"
        - "content/nifti.qmd"
        - "content/mrml-mrb.qmd"
    - part: Radiomics
      chapters:
        - "content/radiomics-wf.qmd"
    - part: Pyradiomics
      chapters: 
        - "content/pyradiomics/pyradiomics-intro.qmd"
        - "content/pyradiomics/PyRadiomicsExample.ipynb"
    - references.qmd


bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc-depth: 4
    code-fold: show

execute: 
  freeze: auto



